// livro-clientes/livros-react/src/LivroLista.js
// LivroLista.js
import React, { useState, useEffect } from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = ({ livro, excluir }) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    const handleExcluir = () => {
        excluir(livro._id);
    };

    return (
        <tr>
            <td className="td-titulo">
                <div className="row">
                    <div className="col">
                        {livro.titulo}
                    </div>
                </div>
                <div className="row">
                    <div className="col">
                        <button className="btn btn-danger btn-sm" onClick={handleExcluir}>Excluir</button>
                    </div>
                </div>                
            </td>
            <td className="td-resumo">{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul>
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        const fetchLivros = async () => {
            const livrosObtidos = await controleLivro.obterLivros();
            setLivros(livrosObtidos);
            setCarregado(true);
        };

        fetchLivros();
    }, [carregado]);

    const excluir = async (id) => {
        await controleLivro.excluir(id);
        setCarregado(false);
    };

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className="table table-striped mt-4">
                <thead>
                    <tr>
                        <th scope="col">Título</th>
                        <th scope="col">Resumo</th>
                        <th scope="col">Editora</th>
                        <th scope="col">Autores</th>
                    </tr>  
                </thead>
                <tbody>
                    {livros.map((livro) => (
                        <LinhaLivro key={livro._id} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;

// livro-clientes/livros-angular/src/app/components/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';

import { Editora } from '../../models/editora';
import { Livro } from '../../models/livro';

import { ControleEditoraService } from '../../services/controle-editora.service';
import { ControleLivrosService } from '../../services/controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})

export class LivroListaComponent implements OnInit {

  public editoras: Array<Editora> = [];
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.carregarLivros();
  }

  carregarLivros(): void {
    this.servLivros.obterLivros()
      .subscribe(
        (livros) => {
          this.livros = livros;
        },
        (error) => {
          console.error('Erro ao carregar livros:', error);
        }
      );
  }

  excluir(id: string): void {
    this.servLivros.excluir(id)
      .subscribe(
        () => {
          console.log('Livro excluído com sucesso.');
          this.carregarLivros(); 
        },
        (error) => {
          console.error('Erro ao excluir livro:', error);
        }
      );
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container mt-4">
    <h1>Catálogo de Livros</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Título</th>
          <th>Editora</th>
          <th>Autores</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.titulo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro._id)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
