// livro-clientes/livros-angular/src/app/components/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../../models/livro';
import { Editora } from '../../models/editora';
import { ControleEditoraService } from '../../services/controle-editora.service';
import { ControleLivrosService } from '../../services/controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {

  livro: Livro = new Livro();
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();

    if (this.editoras.length > 0)
      this.livro.codEditora = this.editoras[0].codEditora;
  }

  onEditoraChange(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.livro.codEditora = Number(target.value);
  }

  incluir(): void {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);

    this.servLivros.incluir(this.livro)
      .subscribe(
        () => {
          console.log('Livro incluído com sucesso.');
          this.router.navigateByUrl('/lista');
        },
        (error) => {
          console.error('Erro ao incluir livro:', error);
        }
      );
  }
}

   <main class="container mt-4">
    <h2 class="mb-4">Dados do Livro</h2>
    <form (ngSubmit)="incluir()" ngNativeValidate>
      <div class="mb-3">
        <label for="titulo" class="form-label">Título:</label>
        <input type="text" class="form-control" id="titulo" name="titulo" [(ngModel)]="livro.titulo" required>
      </div>
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo:</label>
        <textarea class="form-control" id="resumo" name="resumo" rows="4" [(ngModel)]="livro.resumo"></textarea>
      </div>
      <div class="mb-3">
        <label for="editora" class="form-label">Editora:</label>
        <select class="form-select" id="editora" name="editora" [(ngModel)]="livro.codEditora" (change)="onEditoraChange($event)" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="autores" class="form-label">Autores:</label>
        <textarea class="form-control" id="autores" name="autores" rows="2" [(ngModel)]="autoresForm"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
  </main>

// livro-clientes/livros-react/src/LivroDados.js
// LivroDados.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LivroDados = () => {
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(0);
    const navigate = useNavigate();

    const opcoes = controleEditora.getEditoras().map(editora => ({ value: editora.codEditora, text: editora.nome }));

    const tratarCombo = (e) => {
        setCodEditora(Number(e.target.value));
    };

    const incluir = async (e) => {
        e.preventDefault();
        const novoLivro = {
            titulo,
            resumo,
            autores: autores.split("\n").map(author => author.trim()),  
            codEditora
        };

        console.log("Enviando livro:", JSON.stringify(novoLivro));

        try {
            await controleLivro.incluir(novoLivro);
            navigate("/");
        } catch (error) {
            console.error("Erro ao incluir o livro:", error);
        }
    };

    return (
        <main className="container-lg">
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className="mt-4 mb-2">
                    <label htmlFor="titulo" className="form-label">Título</label>
                    <input id="titulo" type="text" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </div>
                <div className="mb-2">
                    <label htmlFor="resumo" className="form-label">Resumo</label>
                    <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
                </div>
                <div className="mb-2">
                    <label htmlFor="editoras" className="form-label">Editora</label>
                    <select id="editoras" className="form-control" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>
                <div className="mb-2">
                    <label htmlFor="autores" className="form-label">Autores (um por linha)</label>
                    <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
                </div>
                <button type="submit" className="btn btn-primary mt-2">Salvar Dados</button>
            </form>
        </main>
    );
};

export default LivroDados;
